ktor {
    deployment {
        host = "0.0.0.0"
        port = 8080
    }

    application {
        modules = [ com.example.filmcatalogserver.ApplicationKt.module ]
    }
}

database {
    jdbcUrl = "jdbc:postgresql://localhost:5432/film_catalog"
    user = "postgres"
    password = "postgres"
}
